import pytest
import gzip
from pathlib import Path
from allenricher.database.goa_fetcher import GOAFetcher


class TestGOAFetcher:
    """GOAFetcher 测试"""

    @pytest.fixture
    def sample_gaf_file(self, tmp_path):
        """创建模拟的 GAF 文件

        GOAFetcher.parse_goa_file 使用 parts[13] 读取 Taxon 字段。
        测试数据统一为18列，Taxon 严格对齐到 index 13。
        列布局: DB(0) ID(1) Symbol(2) Qual(3) GO(4) Ref(5) Evi(6) With(7)
                Aspect(8) Name(9) Synonym(10) Synonym2(11) Type(12)
                Taxon(13) Date(14) Assigned(15) Ext(16) Prop(17)
        """
        gaf_path = tmp_path / "test.gaf"
        gaf_content = (
            "!gaf-version: 2.2\n"
            "!Generated by: UniProtKB\n"
            # GOT2: 2个GO term, taxon:9606 (18列)
            "UniProtKB\tP12345\tGOT2\tinvolved_in\tGO:0006457\tPMID:9683573\t"
            "IEA\tUniProtKB-KW:KW-0377\tF\tP\tGOT2_HUMAN\tmAspAT\tprotein\t"
            "taxon:9606\t20111018\tUniProtKB\t\t\n"
            # TP53: 1个GO term, taxon:9606 (18列)
            "UniProtKB\tP67890\tTP53\tenables\tGO:0003677\tPMID:1234567\t"
            "EXP\t\t\tF\tCellular tumor antigen p53\tp53\tprotein\t"
            "taxon:9606\t20120101\tHGNC\t\t\n"
            # BRCA1: 1个GO term, taxon:9606 (18列)
            "UniProtKB\tQ9Y6K1\tBRCA1\tinvolved_in\tGO:0006974\tPMID:2345678\t"
            "IDA\t\t\tP\tDNA repair protein BRCA1\tBRCA1\tprotein\t"
            "taxon:9606\t20130101\tHGNC\t\t\n"
            # RPL10A: 2个GO term, taxon:9606 (18列)
            "UniProtKB\tP62988\tRPL10A\tenables\tGO:0003735\tGOREF:0000033\t"
            "IEA\tInterPro:IPR002131\t\tF\t60S ribosomal protein L10a\tRPL10A\tprotein\t"
            "taxon:9606\t20140101\tUniProtKB\t\t\n"
            # RPL10A: 第2个GO term, taxon:9606 (18列)
            "UniProtKB\tP62988\tRPL10A\tinvolved_in\tGO:0006412\tGOREF:0000033\t"
            "IEA\tInterPro:IPR002131\t\tP\t60S ribosomal protein L10a\tRPL10A\tprotein\t"
            "taxon:9606\t20140101\tUniProtKB\t\t\n"
            # GOT2: 第2个GO term, taxon:9606 (18列)
            "UniProtKB\tP12345\tGOT2\tlocated_in\tGO:0005739\tPMID:9683573\t"
            "IEA\tUniProtKB-KW:KW-0377\tC\tP\tGOT2_HUMAN\tmAspAT\tprotein\t"
            "taxon:9606\t20111018\tUniProtKB\t\t\n"
            # UNKNOWN: taxon:10090, 应被过滤 (18列)
            "UniProtKB\tP99999\tUNKNOWN\tenables\tGO:0003674\tGOREF:0000033\t"
            "IEA\t\t\tF\tUnknown protein\t-\tprotein\t"
            "taxon:10090\t20150101\tUniProtKB\t\t\n"
            # 11111: Symbol以数字开头, 应被跳过 (18列)
            "UniProtKB\tP11111\t11111\tenables\tGO:0003674\tGOREF:0000033\t"
            "IEA\t\t\tF\t-\t-\tprotein\t"
            "taxon:9606\t20150101\tUniProtKB\t\t\n"
        )
        gaf_path.write_text(gaf_content)
        return gaf_path

    def test_parse_goa_file_filters_by_taxid(self, sample_gaf_file):
        """测试按TaxID过滤"""
        fetcher = GOAFetcher(cache_dir="/tmp/test_goa")
        gene_to_go, all_genes = fetcher.parse_goa_file(sample_gaf_file, taxid=9606)

        # 应该有4个基因（GOT2, TP53, BRCA1, RPL10A），排除 UNKNOWN（taxid 10090）
        assert len(all_genes) == 4
        assert "GOT2" in all_genes
        assert "TP53" in all_genes
        assert "BRCA1" in all_genes
        assert "RPL10A" in all_genes
        assert "UNKNOWN" not in all_genes

    def test_parse_goa_file_skips_symbol_equals_id(self, sample_gaf_file):
        """测试跳过Symbol等于ID的行"""
        fetcher = GOAFetcher(cache_dir="/tmp/test_goa")
        gene_to_go, all_genes = fetcher.parse_goa_file(sample_gaf_file, taxid=9606)

        # P11111 的 Symbol 是 "11111"（等于ID的一部分，以数字开头），应该被跳过
        assert "11111" not in all_genes

    def test_parse_goa_file_gene_to_go_mapping(self, sample_gaf_file):
        """测试基因到GO的映射"""
        fetcher = GOAFetcher(cache_dir="/tmp/test_goa")
        gene_to_go, all_genes = fetcher.parse_goa_file(sample_gaf_file, taxid=9606)

        # GOT2 应该有2个GO term
        assert len(gene_to_go.get("GOT2", set())) == 2
        assert "GO:0006457" in gene_to_go["GOT2"]
        assert "GO:0005739" in gene_to_go["GOT2"]

        # RPL10A 应该有2个GO term
        assert len(gene_to_go.get("RPL10A", set())) == 2

    def test_build_go2gene_matrix(self, tmp_path):
        """测试GO2gene矩阵生成"""
        gene_to_go = {
            "GOT2": {"GO:0006457", "GO:0005739"},
            "TP53": {"GO:0003677"},
            "BRCA1": {"GO:0006974"},
        }
        all_genes = {"GOT2", "TP53", "BRCA1"}
        all_go_terms = {"GO:0006457", "GO:0003677", "GO:0005739", "GO:0006974"}
        output_path = tmp_path / "GO2gene.tab.gz"

        GOAFetcher.build_go2gene_matrix(gene_to_go, all_genes, all_go_terms, output_path)

        assert output_path.exists()
        # 读取并验证
        with gzip.open(output_path, 'rt') as f:
            header = f.readline().strip().split('\t')
            assert header[0] == "Gene"
            assert "GO:0006457" in header

            lines = f.readlines()
            assert len(lines) == 3  # 3个基因

            # GOT2 行
            got2_line = [l for l in lines if l.startswith("GOT2")][0]
            fields = got2_line.strip().split('\t')
            got2_idx = header.index("GO:0006457")
            assert fields[got2_idx] == "1"

    def test_build_gene2go_list(self, tmp_path):
        """测试gene2go列表生成"""
        gene_to_go = {
            "GOT2": {"GO:0006457", "GO:0005739"},
            "TP53": {"GO:0003677"},
        }
        go_names = {
            "GO:0006457": "protein binding",
            "GO:0005739": "mitochondrion",
            "GO:0003677": "DNA binding",
        }
        output_path = tmp_path / "gene2go.txt"

        GOAFetcher.build_gene2go_list(gene_to_go, go_names, output_path)

        assert output_path.exists()
        content = output_path.read_text()
        lines = content.strip().split('\n')
        assert len(lines) == 3  # 3条注释

        # GOT2 应该有2行
        got2_lines = [l for l in lines if l.startswith("GOT2")]
        assert len(got2_lines) == 2
